# ---------- 定时任务相关 ----------
signin_time: 0 10 0 * * ?
task_time: 0 10 0 * * ?
sanity_push_time: 0 */7 * * * ?
news_push_time: 0 */15 * * * ?

# ---------- 通用配置 ----------
# 签到间隔时间
signin_interval: 37
# 任务间隔时间
task_interval: 37
# 攻略图提供方
strategy_provide: all
# 是否使用公共cookie
use_public_cookie: true
# 是否允许用户导入抽卡记录
allow_import: false
# 是否开启成功日志输出
enable_log: false
# 图片渲染精度
render_scale: 100
# 接口并发量
limit: 10

# ---------- 登录服务器配置 ----------
# 允许在线登录
allow_login: false
# 服务器开放端口
server_port: 25088
# 登录地址获取
public_link: 'http://127.0.0.1:25088'
# 背景图API
background_api: 'https://www.loliapi.com/acg'

# ---------- 面板图相关 ----------
# 是否允许普通用户上传面板图
allow_img_upload: false
# 是否允许普通用户获取原图
allow_get_origin: true
# 是否允许普通用户获取面板图列表
allow_get_list: false
# 是否允许普通用户删除面板图
allow_img_delete: false

# ---------- 别名相关 ----------
# 是否允许普通用户设置别名
allow_set_alias: false